INSERT INTO films (name, description, year, genre_id, minimal_age, duration_in_minutes, file_id)
VALUES ('127 Hours',
        'A mountain climber becomes trapped under a boulder while canyoneering alone near Moab, Utah and resorts to desperate measures in order to survive.',
        2010, 1, 16, 93, 1),
       ('Bone Tomahawk',
        'In the dying days of the old west, an elderly sheriff and his posse set out to rescue their town''s doctor from cannibalistic cave dwellers.',
        2015, 1, 18, 133, 2),
       ('Conan the Barbarian',
        'A vengeful barbarian warrior sets off to get his revenge on the evil warlord who attacked his village and murdered his father when he was a boy.',
        2011, 2, 18, 112, 3),
       ('Godzilla',
        'The world is beset by the appearance of monstrous creatures, but one of them may be the only one who can save humanity.',
        2014, 2, 16, 123, 4),
       ('Hobo with a Shotgun',
        'A homeless vigilante blows away crooked cops, pedophile Santas, and other scumbags with his trusty pump-action shotgun.',
        2011, 2, 18, 86, 5),
       ('Jodorowsky''s Dune',
        'The story of cult film director Alejandro Jodorowsky''s ambitious but ultimately doomed film adaptation of the seminal science fiction novel.',
        2013, 3, 12, 90, 6),
       ('Kingsman The Secret Service',
        'A spy organisation recruits a promising street kid into the agency''s training program, while a global threat emerges from a twisted tech genius.',
        2014, 2, 18, 130, 7),
       ('Red Army',
        'The story of the Soviet Union''s famed Red Army hockey team through the eyes of its players.',
        2014, 3, 12, 84, 8),
       ('The Martian',
        'An astronaut becomes stranded on Mars after his team assume him dead, and must rely on his ingenuity to find a way to signal to Earth that he is alive and can survive until a potential rescue.',
        2015, 1, 16, 144, 9),
       ('Thor Ragnarok',
        'Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarök, the destruction of his world, at the hands of the powerful and ruthless villain Hela.',
        2017, 2, 16, 130, 10);